blank_issues_enabled: false
contact_links:
  - name: Modrinth Page
    url: https://modrinth.com/mod/personalbeacon
    about: Download the latest version of PersonalBeacon on Modrinth.
  - name: Upload Crash Logs
    url: https://mclo.gs
    about: Use mclo.gs to upload large crash logs and paste the link in your bug report.
